import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/settings/settings_screen.dart';
import 'package:provider/provider.dart';
import '../../providers/theme_notifier.dart';
import 'package:easy_localization/easy_localization.dart';
import 'screens/account/account_screen.dart';
import 'firebase_options.dart'; // Firebase configuration options
import 'services/db_service.dart'; // Local SQLite DB service
import 'widgets/auth_layout.dart'; // Entry point widget for login/logic handling

void main() async {
  // Ensure Flutter widget binding is initialized before Firebase/DB init
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  try {
    // Initialize Firebase using config generated by FlutterFire CLI
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Initialize SQLite database via your DBService singleton
    await DBService().database;
  } catch (e) {
    // Log or handle initialization errors (useful for debugging on device)
    print("Initialization error: $e");
    // Optionally, show an error screen here if initialization fails
  }

  // Run the main app widget
  runApp(
    EasyLocalization(
      supportedLocales: const [Locale('en'), Locale('ms'), Locale('zh')],
      path: 'assets/lang',
      fallbackLocale: const Locale('en'),
      child: ChangeNotifierProvider(
        create: (_) => ThemeNotifier(),
        child: const SpendlyticApp(),
      ),
    ),
  );
}

class SpendlyticApp extends StatelessWidget {
  const SpendlyticApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeNotifier>(
      builder: (context, themeNotifier, _) {
        return MaterialApp(
          title: 'Spendlytic',
          debugShowCheckedModeBanner: false,

          // 🔁 Respond to toggle
          themeMode: themeNotifier.currentTheme,

          theme: ThemeData(
            brightness: Brightness.light,
            scaffoldBackgroundColor: const Color(0xFFF5F4FA),
            colorScheme: const ColorScheme.light(
              primary: Color.fromARGB(255, 188, 147, 255),
              secondary: Color.fromARGB(255, 217, 191, 250),
              surface: Colors.white,
              onPrimary: Colors.black,
              onSurface: Color(0xFF333333),
            ),
          ),

          darkTheme: ThemeData(
            brightness: Brightness.dark,
            scaffoldBackgroundColor: const Color(0xFF121212),
            colorScheme: const ColorScheme.dark(
              primary: Color(0xFFBF00FF),
              secondary: Color.fromARGB(255, 196, 48, 255),
              surface: Color(0xFF1E1E1E),
              onPrimary: Color.fromARGB(255, 255, 255, 255),
              onSurface: Color.fromARGB(255, 255, 255, 255),
            ),
          ),

          locale: context.locale,
          supportedLocales: context.supportedLocales,
          localizationsDelegates: context.localizationDelegates,

          routes: {
            '/settings': (context) => const SettingsScreen(),
            '/account_settings': (context) => const AccountScreen(),
          },
          home: const AuthLayout(),
        );
      },
    );
  }
}
