import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';         // Firebase configuration options
import 'services/db_service.dart';      // Local SQLite DB service
import 'widgets/auth_layout.dart';      // Entry point widget for login/logic handling

void main() async {
  // Ensure Flutter widget binding is initialized before Firebase/DB init
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initialize Firebase using config generated by FlutterFire CLI
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

    // Initialize SQLite database via your DBService singleton
    await DBService().database;
  } catch (e) {
    // Log or handle initialization errors (useful for debugging on device)
    print("Initialization error: $e");
    // Optionally, show an error screen here if initialization fails
  }

  // Run the main app widget
  runApp(const SpendlyticApp());
}

class SpendlyticApp extends StatelessWidget {
  const SpendlyticApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Spendlytic',

      // Remove debug banner for production use
      debugShowCheckedModeBanner: false,

      // Respect system-wide light/dark preference
      themeMode: ThemeMode.system,

      // Light theme settings
      theme: ThemeData(
        brightness: Brightness.light,
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: const Color(0xFFF5F4FA),
        colorScheme: ColorScheme.light(
          primary: Color.fromARGB(255, 188, 147, 255),   // pastel purple
          secondary: Color.fromARGB(255, 217, 191, 250), // lighter purple
          surface: Colors.white,
          onPrimary: Colors.black,
          onSurface: Color(0xFF333333), // dark text on light bg
        ),
      ),

      // Dark theme settings
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: Color(0xFF121212),
        colorScheme: ColorScheme.dark(
          primary: Color(0xFFBF00FF),                     // Electric Purple
          secondary: Color.fromARGB(255, 196, 48, 255),   // vibrant accent
          surface: Color(0xFF1E1E1E),
          onPrimary: Colors.white,
          onSurface: Colors.white,
        ),
      ),

      // First widget shown after startup
      home: const AuthLayout(), // This should decide if the user is logged in or not
    );
  }
}
